

//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------


namespace EURIS.Entities
{

using System;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;


public partial class LocalDbEntities : DbContext
{
    public LocalDbEntities()
        : base("name=LocalDbEntities")
    {

    }

    protected override void OnModelCreating(DbModelBuilder modelBuilder)
    {
        throw new UnintentionalCodeFirstException();
    }


    public DbSet<Product> Product { get; set; }

    public DbSet<Catalog> Catalog { get; set; }

    public DbSet<ProductCatalog> ProductCatalog { get; set; }

}

}

