
//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------


namespace EURIS.Entities
{

using System;
    using System.Collections.Generic;
    
public partial class ProductCatalog
{

    public int ProductCatalogId { get; set; }

    public int ProductId { get; set; }

    public int CatalogId { get; set; }



    public virtual Catalog Catalog { get; set; }

    public virtual Product Product { get; set; }

}

}
